### ISSUE TITLE
Feature: User can view past entries

### ISSUE THREAD

**Issue by tevnicolas** [tevnicolas/Your-Climate-Future#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on 'entries' will show their list of entries in reverse chronological order.

## 🖼️ Wireframes
![Screenshot 2024-03-07 at 11 51 27 AM](https://github.com/tevnicolas/front-end-project/assets/155599138/79f9897b-c319-4206-bc38-b6747ee670b5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Define a function named `renderEntry` with a single parameter named `entry`. This parameter represents a single object for a single entry from the `data.entries` array. Should generate and return a DOM tree for a single entry that matches the entries you created in the unordered list.
- [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.entries` array and generate a DOM tree for each entry in the array, and append that DOM tree to the unordered list.
- [x] Remove the example HTML entries from `index.html` once the user's entries are successfully being appended to the DOM on page load and replace them with a message indicating that no entries have been recorded which matches the figma.
- [x] Create a new function named `viewSwap` with a single parameter representing the name of the view to show (the value will be either 'entries-page', 'loading-page', 'landing-page', or 'form-page'.
- [x] Add an anchor to the navbar to show the `”entries”` view. Create an event handler function that utilizes the `viewSwap` function to show the proper view.
    - [x] Render a DOM tree for the newly submitted entry object using the `renderEntry` function.
   - [x] Prepends the new DOM tree to the entries-page
   - [x] toggleNoEntries
- [x] Add an anchor to the entries view to show the `entries-page`.
- [x] Create a function named `toggleNoEntries` which toggles the no entries text to show or hide when the function is called.
- [x] Update the `submit` callback for the form to do the following:
  - [x] Render a DOM tree for the newly submitted entry object using the `renderEntry` function.
  - [x] Hide previous entries
  - [x] Prepends the new DOM tree to the form-page.
- [x] Update the `DOMContentLoaded` callback function to do the following:
  - [x] uses the `viewSwap` function to show the view which was displayed prior to page refresh.
  - [x] conditionally uses the `toggleEntries` function as needed to show or remove the no entries text.
  - [x] Add ability to select an entry on the entries-page and view it in full
- [x] Convert API data into meaningful description results.
- [x] Generate Image based data (Chart) with an additional graphing API
- [x] Add a year value to the object, which should be 2100 for all newly generated entries from the landing page.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
