### ISSUE TITLE
Feature: User can edit entries

### ISSUE THREAD

**Issue by tevnicolas** [tevnicolas/Your-Climate-Future#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit climate future entries to regenerate based on a new data and location.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking an edit button on an entry (on the entries page) will bring the user to a full view fields available to edit. They will then be able to click save to regenerate the entry.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-12 at 11 47 28 AM](https://github.com/tevnicolas/Your-Climate-Future/assets/155599138/8cc93a40-6ef8-43fe-8e9c-4b5181782577)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the `render` function to do the following:
  - [x] Add a edit icon next to the title of each entry which matches the figma example.
- [x] Edit the event listener to the `$entriesHook` and the listener on the `$formHook` to do the following when an entry's edit icon is clicked:
  - [x] Use the `viewSwap` function to show a new edit-form page.
  - [x] Include a new form page in the edit-form html that adds the option for date change as a select element
  - [x] Find the entry object in the `data.entries` array whose id matches the `data-entry-id` attribute value of the clicked entry and assigns that entry’s object to the `data.editing` property.
  - [x] Pre-populate the edit form with the clicked entry's values from the object stored in the `data.editing` property.
  - [x] Includes a save button on the page (submit button).
- [x] Create a new submit handler on the editing-pages save button to do the following:
    - [x] Assign the entry id value from `data.editing` to the new object with the updated form values.
    - [x] Replace the original object in the `data.entries` array for the edited entry with the new object with the edited data.
    - [x] Render 2 new DOM trees for both form-page and entry-page for the new object with the updated data, and replace the original `div (.short-row)` and `div(.row)` with the matching `data-entry-id` value with the new generated DOM tree.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
