### ISSUE TITLE
Feature: User can delete entries

### ISSUE THREAD

**Issue by tevnicolas** [tevnicolas/Your-Climate-Future#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on the 'Delete Entry' Button and delete the entry permanently from the site. They will be switched to the entries-page after doing so.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-14 at 9 44 24 AM](https://github.com/tevnicolas/Your-Climate-Future/assets/155599138/e70f1df1-1159-42a8-bc5f-2c82ece86789)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Show a confirmation modal when the user clicks **Delete Entry**
- [x] When the user clicks **Cancel**, hide the modal.
- [x] When the user clicks **Confirm**:
  - [x] remove the corresponding entry object from the data model's entry array.
  - [x] remove the entry's `div (.row)/ div (.short-row)` elements from both DOM trees.
  - [x] conditionally uses the `toggleNoEntries` function to show the no entries text if needed.
  - [x] hide the modal.
  - [x] swap to the Entries view.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
